version: "3"
services:
  index:
    image: ymslanda.innovationgarage.tech:5000/portpollution_weatherindex:latest
    environment:
      DATABASE: "${DATABASE}"
      BASEDIR: "/data"
    volumes:
      - /ymslanda/PortPollution/WeatherScrape:/data
